# Generated by Django 2.2.2 on 2019-06-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190613_1440'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Writer',
        ),
    ]
