# Generated by Django 2.2.2 on 2019-06-16 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_delete_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='returned',
            field=models.DateField(default=datetime.datetime(2019, 6, 16, 21, 50, 28, 734130)),
        ),
    ]
