# Generated by Django 2.2.2 on 2019-06-16 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='returned',
            field=models.DateField(default=datetime.datetime(2019, 6, 16, 21, 52, 13, 185388)),
        ),
    ]
