# Generated by Django 2.2.2 on 2019-06-16 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190616_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='returned',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 6, 16, 21, 56, 29, 419360)),
        ),
    ]
