# Generated by Django 2.2.2 on 2019-06-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20190616_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='returned',
            field=models.DateField(blank=True),
        ),
    ]
